language: java

# We use OpenJDK instead of Oracle JDK because ya all should only
# ever use OpenJDK!  (And get Red Hat's support for it, if
# you use it professionally.)
jdk: 
  - openjdk8

before_install:
  - git clone --recursive https://github.com/vorburger/ch.vorburger.minecraft.osgi/
  - cd ch.vorburger.minecraft.osgi/ch.vorburger.osgi.gradle && ./gradlew install
  - cd .. && ./gradlew install
